apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dummy-certificate
  labels:
    test: first
spec:
  dnsNames:
  - example.com
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned
  secretName: sname1234